### ISSUE TITLE
License

### ISSUE THREAD

**Issue by altre** [AkihikoWatanabe/DBGD#2]
Hi, nice library!
You don't have a license in your repository. We might want to integrate part of your code in a commercial setting. Do you think you could decide on a license?

**Comment by AkihikoWatanabe** [comment]
Thank you for pointing out license in this repository.
Now this software is released under the MIT License.

In previous implementation, the library that calculate MRR and MAP was borrowed from https://gist.github.com/bwhite/3726239, but this code don't have license.
Therefore, I implemented my own scripts that calculate MRR and MAP in order to release this software under the MIT license.
